export const ADD_NEWS = 'ADD_NEWS';
export const NEWS_FETCH_FAILURE = 'NEWS_FETCH_FAILURE';
export const FETCH_NEWS = 'FETCH_NEWS';
export const START_FETCH_PROGRESS = 'START_FETCH_PROGRESS';
export const END_FETCH_PROGRESS = 'END_FETCH_PROGRESS';
export const OPEN_NEWS_CARD_MODAL = 'OPEN_NEWS_CARD_MODAL';
export const CLOSE_NEWS_CARD_MODAL = 'CLOSE_NEWS_CARD_MODAL';